### ISSUE TITLE
macOS 10.14.5 安装后不生效

### ISSUE THREAD

**Issue by yisibl** [dreampiggy/AVIFQuickLook#1]
使用空格预览文件没有缩略图。

![image](https://user-images.githubusercontent.com/2784308/72506835-a8116080-387d-11ea-9ceb-6e086194af75.png)

**Comment by dreampiggy** [comment]
是不是签名问题导致的？我记得macOS 10.15还是什么时候，要求所有二进制，包括命令行，以及这种插件，都需要走[苹果服务器认证后的签名](https://developer.apple.com/news/?id=09032019a)。这个当时产出的二进制没有签名。

你先尝试本地测试下，用这个命令，把终端输出的日志发给我看看

```bash
qlmanage -t foo.avif -d 4
```

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/72512329-d8113180-3886-11ea-889c-5d1629c99c68.png)


https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution?language=objc

> Beginning in macOS 10.14.5, software signed with a new Developer ID certificate and all new or updated kernel extensions must be notarized to run. Beginning in macOS 10.15, all software built after June 1, 2019, and distributed with Developer ID must be notarized. However, you aren’t required to notarize software that you distribute through the Mac App Store because the App Store submission process already includes equivalent security checks.

如果是这个问题的话，麻烦先临时绕过一下，在系统偏好设置.app中，选择“始终允许”，或者你临时执行这个命令，然后预览你的AVIF文件，完成一次后，再还原回去这个设置。我之后重新找个付费的开发者证书，打包一个二进制上传上来

```
sudo spctl --master-disable
```

```
sudo spctl --master-enable
```

**Comment by dreampiggy** [comment]
@yisibl Try this one instead ? Which rebuilt using the Developer Account.

[AVIFQuickLook.qlgenerator.zip](https://github.com/dreampiggy/AVIFQuickLook/files/4070346/AVIFQuickLook.qlgenerator.zip)

**Comment by yisibl** [comment]
可以了 thx
