### ISSUE TITLE
XCode 13 CoreGraphics import 

### ISSUE THREAD

**Issue by martin-haynes** [dreampiggy/AVIFQuickLook#11]
Latest xcode required me to import this library explicitly.

`@import CoreGraphics;`
https://github.com/dreampiggy/AVIFQuickLook/blob/9cf74834607ae7b6f8712aa8b8ea0aad6554984f/AVIFDecoder/AVIFDecoder.h#L9

**Comment by dreampiggy** [comment]
Should be solved by #12
