### ISSUE TITLE
Cannot preview in MacOS 12.6

### ISSUE THREAD

**Issue by bd-dxg** [dreampiggy/AVIFQuickLook#13]
MacOS Version: 12.6
AvifQuickLook:1.1

The thumbnail can be previewed in finder, but it cannot be opened through preview app.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/34816426/197451918-f42f3233-3c58-431e-a652-e7ae5f3246e0.png">

**Comment by bd-dxg** [comment]
MacOS 13 has native support for image preview of avif.

**Comment by dreampiggy** [comment]
This AVIF preview can only show thumbnail and using space command to show on full screen Finder preview.

It can not open Preview.app or support any information/editor in Preview.app.

Finder preview VS Preview.app, they are different things.
