### ISSUE TITLE
After install via brew and qlmanage reload cache, the thumbnail updated, but become gray 

### ISSUE THREAD

**Issue by weaming** [dreampiggy/AVIFQuickLook#15]
<img width="372" alt="image" src="https://github.com/dreampiggy/AVIFQuickLook/assets/10275711/423898e7-0364-4ee8-8c54-8f2b3cb92d31">
<img width="294" alt="image" src="https://github.com/dreampiggy/AVIFQuickLook/assets/10275711/ffadb8b6-58d3-45a1-b0bd-7497f846f489">

first origin heif, second avif

**Comment by dreampiggy** [comment]
Seems the libavif render issue about HDR contents. Need dependency bump. I'll update next week.

**Comment by weaming** [comment]
any update ?

**Comment by dreampiggy** [comment]
@weaming Provide you sample AVIF to me, let me debug that

**Comment by weaming** [comment]
you can download from https://dl.bitsflow.org/example.avif

**Comment by dreampiggy** [comment]
Seems the code from SDWebImageAVIF, does not have the HDR contents support...It hardcode on 8bit sRGB only :)

Or maybe that `YUV -> RGB` conversion loss the Color Profile ?

SD is also maintained by me, but HDR content support will ship in next major release. I can patch to quickly support HDR by copying the code here😂

Fired issue: https://github.com/SDWebImage/SDWebImageAVIFCoder/issues/54

**Comment by dreampiggy** [comment]
#16 should fix this issue.

@weaming Have a try with this new build (See readme about how to put that qlgenerator)

[AVIFQuickLook.qlgenerator.zip](https://github.com/dreampiggy/AVIFQuickLook/files/12136907/AVIFQuickLook.qlgenerator.zip)

**Comment by dreampiggy** [comment]
![image](https://github.com/dreampiggy/AVIFQuickLook/assets/6919743/22fa7f83-7496-4376-9e8f-7c328ba3a184)

**Comment by weaming** [comment]
works for me

**Comment by dreampiggy** [comment]
Ship with 1.2.0 version

**Comment by dreampiggy** [comment]
Homebrew and release page updated
