### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by artem-tepponen** [dreampiggy/AVIFQuickLook#2]
Great plugin, but I've got into problems installing it on macOS Catalina 10.15.4 (19E287)
I didn't even had ~/Library/QuickLook folder, created this folder and put the plugin here, nothing happened. Tried to run the binary with Control key so it gets "registered", didn't help.
Only after I put the plugin into /Library/QuickLook it started to work

Maybe Readme file needs some corrections?

**Comment by transitive-bullshit** [comment]
This worked for me as well. Additionally I had to open the package contents and run the AVIF.app directly and then bypass the OS warning screen by selecting Open to whitelist the app.

Thanks!

**Comment by dreampiggy** [comment]
Added the readme for this: https://github.com/dreampiggy/AVIFQuickLook/commit/8ffbf36aeed510398dbed750799f55aa5cb571c5.

Thanks for reply. This tools is for my personal usage. So maybe this will no active response and commit 😂

**Comment by transitive-bullshit** [comment]
Thanks @dreampiggy -- this is super useful and the only one of its kind I was able to find. 🙏

**Comment by dreampiggy** [comment]
This tools is mostly based on a third party codec: https://github.com/AOMediaCodec/libavif

It already upgrade many versions, but currently this plugin use an old libavif. I can bump and use the latest commit to build another version, or setup something like GitHub action to automatic release.

Need some time to do :)
