### ISSUE TITLE
How to update the lib files?

### ISSUE THREAD

**Issue by radum** [dreampiggy/AVIFQuickLook#3]
Hello,

There are 3 dependency files `libaom.a` `libavif.a` `libgb.a`. From where do you got those so we can update if we want?

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/libavif-Xcode
Open the Xcode Project and archive the static framework.

The exist static library I use the libavif's own CMake to build, however, you can choose what you want.

**Comment by dreampiggy** [comment]
I use the SwiftPM's libavif 0.9.3 version in the new commit

You can also build and bump your own version as well.
