### ISSUE TITLE
Add to brew?

### ISSUE THREAD

**Issue by mvshmakov** [dreampiggy/AVIFQuickLook#4]
Thanks for a great extension!
Could you add it to brew.sh? It would be easier to update/install it.

**Comment by tcyrus** [comment]
A good example is the [WebP QuickLook Plugin](https://github.com/dchest/webp-quicklook), which can be installed by running `brew cask install webpquicklook`

**Comment by tcyrus** [comment]
Made a quick cask formula to start with [here](https://gist.github.com/tcyrus/65893b41ef4c64e29e63d5b62430330d)

**Comment by dreampiggy** [comment]
Thanks for your support.

The AVIFQuickLook 1.1.0 version is available. Please have a try:
https://github.com/dreampiggy/AVIFQuickLook/releases/tag/1.1.0

### Homebrew

I submit to the Homebrew Cask here: 

https://github.com/Homebrew/homebrew-cask/pull/123036

Please wait for the review or comment there if you like this QuickLook Plugin

**Comment by dreampiggy** [comment]
@mvshmakov
@tcyrus

Hi. Long time after the previous commit. New version of AVIFQuickLook support Homebrew Cask:

You can have a try with

```
brew install avifquicklook
```
