### ISSUE TITLE
Permission denied error on BigSur (solved)

### ISSUE THREAD

**Issue by RedNaxel80** [dreampiggy/AVIFQuickLook#6]
**Problem**

I could not get it to work on MacOS Big Sur. Images didn't open in preview, showing a blank icon. 
Running "qlmanage -p test.avif" in terminal shown following errors:

> qlmanage[1322:18428] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6b03, name = 'com.apple.coredrag'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2021-01-09 03:16:14.330 qlmanage[1322:18428] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x801b, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.

**Solution**

After a while of googling, I've found this to solve the problem completely - simply run this command in terminal:

xattr -d -r com.apple.quarantine ~/Library/QuickLook/AVIFQuickLook.qlgenerator

Note, the location above ~/Library/QuickLook/ is if you've copied the AVIFQuickLook there for just your user. If you copied the file for all users, to /Library/QuickLook, obviously change the path accordingly.

**Comment by dreampiggy** [comment]
Thanks for this issue report. This seems because of the Developer Distribution. If you compile from source by yourself using Xcode, this does not cause issue.

I'll update the README about this.
