### ISSUE TITLE
Doesn't work for me on 11.6.2

### ISSUE THREAD

**Issue by dhowe** [dreampiggy/AVIFQuickLook#8]
Added to /Library/QuickLook
then ran `$ xattr -d -r com.apple.quarantine /Library/QuickLook/AVIFQuickLook.qlgenerator`
then relaunched finder

still blank

**Comment by dreampiggy** [comment]
Thanks for your support.

The AVIFQuickLook 1.1.0 version is available. Please have a try:
https://github.com/dreampiggy/AVIFQuickLook/releases/tag/1.1.0

### Homebrew

I submit to the Homebrew Cask here: 

https://github.com/Homebrew/homebrew-cask/pull/123036

Please wait for the review or comment there if you like this QuickLook Plugin

**Comment by dreampiggy** [comment]
Have a try with v1.2.0
https://github.com/dreampiggy/AVIFQuickLook/files/12136907/AVIFQuickLook.qlgenerator.zip

See readme about how to install the qlgenerator, or using Homebrew to upgrade.
