### ISSUE TITLE
Worked for me on 12.0.1

### ISSUE THREAD

**Issue by keithgibson** [dreampiggy/AVIFQuickLook#9]
- Using [the 1.0.1](https://github.com/dreampiggy/AVIFQuickLook/releases/download/1.0.1/AVIFQuickLook.qlgenerator.zip) release.

- Copied that to /Library/QuickLook/ (no tilde ~)

- Worked once I ran this in Terminal, per the Mac OS Big Sur instructions, but agains minus the tilde ~:
xattr -d -r com.apple.quarantine /Library/QuickLook/AVIFQuickLook.qlgenerator

Thanks @dreampiggy !

<img width="1352" alt="Screen Shot 2022-02-01 at 1 58 16 PM" src="https://user-images.githubusercontent.com/1214624/152058356-0e187b4e-6847-48f9-b2d3-f89158b78801.png">

**Comment by dreampiggy** [comment]
Thanks for your support.

The AVIFQuickLook 1.1.0 version is available. Please have a try:
https://github.com/dreampiggy/AVIFQuickLook/releases/tag/1.1.0
